# Generated by Django 4.0.1 on 2022-01-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_user_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
