# Generated by Django 4.0.1 on 2022-01-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_user_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_image',
            name='user_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
